# Generated by Django 5.2.6 on 2025-10-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librofirmas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='material',
            name='creado_por',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='LibroFirmas',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
