# Generated by Django 5.2.6 on 2025-10-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_librofirmas_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
