# Generated by Django 5.2.6 on 2025-12-02 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0002_tokenasistencia_asistencia_delete_firmadiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('expira', models.DateTimeField()),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='tokenasistencia',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='tokenasistencia',
            name='expiracion',
        ),
        migrations.RemoveField(
            model_name='tokenasistencia',
            name='usado',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='token_usado',
            field=models.CharField(default='legacy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenasistencia',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tokenasistencia',
            name='expirado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tokenasistencia',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
