# Generated by Django 5.2.6 on 2025-12-04 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0004_asistencia_hora_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora',
        ),
    ]
