# Generated by Django 5.2.6 on 2025-11-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='privado',
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
