# Generated by Django 5.2.6 on 2025-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_evento_privado_alter_evento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='privado',
            field=models.BooleanField(default=False),
        ),
    ]
