# Generated by Django 5.2.6 on 2025-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='anio',
            field=models.IntegerField(choices=[(1, '1° Año'), (2, '2° Año'), (3, '3° Año'), (4, '4° Año'), (5, '5° Año'), (6, '6° Año')], default=1),
            preserve_default=False,
        ),
    ]
